### ISSUE TITLE
Missing sessions table for migration

### ISSUE THREAD

**Issue by dualznz** [clockobot/clockobot#7]
when migrating the database, you cannot access the website due to missing sessions table.

code required to be added to `database/migrations/2014_10_12_000000_create_users_table.php`

[updates to users table.txt](https://github.com/user-attachments/files/16826163/updates.to.users.table.txt)

**Comment by DanDvoracek** [comment]
Just change the value of SESSION_DRIVER in the .env to "file"

`SESSION_DRIVER=file`

I will make the change in the default .env.example . Thanks for pointing it out

**Comment by DanDvoracek** [comment]
Added the change in https://github.com/clockobot/clockobot/releases/tag/v1.0.3 . Closing the issue.
